# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-03 13:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interfaceBrand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotelid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hootelname', models.CharField(max_length=50, verbose_name='\u9152\u5e97\u540d')),
                ('kdt', models.CharField(max_length=5, verbose_name='KDT')),
                ('hotelid', models.CharField(max_length=10, verbose_name='\u9152\u5e97id')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u9152\u5e97\u4fe1\u606f',
                'verbose_name_plural': '\u9152\u5e97\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='OpenInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booleaninter', models.CharField(choices=[('on', '\u5f00'), ('off', '\u5173')], default='off', max_length=6, verbose_name='\u5f00\u542f\u72b6\u6001')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('hootelname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.Hotelid', verbose_name='\u6240\u5c5e\u9152\u5e97')),
                ('verison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interfaceBrand.BrandVersion', verbose_name='\u76d1\u63a7\u63a5\u53e3')),
            ],
            options={
                'verbose_name': '\u63a5\u53e3\u76d1\u63a7',
                'verbose_name_plural': '\u63a5\u53e3\u76d1\u63a7',
            },
        ),
        migrations.CreateModel(
            name='StatusInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sjdinterfacesta', models.CharField(max_length=20, verbose_name='\u63a5\u53e3\u72b6\u6001')),
                ('port', models.IntegerField(default=0, verbose_name='\u76d1\u63a7\u7aef\u53e3')),
                ('portvercode', models.CharField(default='266fe0e1-f047-11e7-bd61-201a0621d396', max_length=150, verbose_name='\u63a5\u53e3\u9a8c\u8bc1\u7801')),
                ('up_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('cq_time', models.DateTimeField(verbose_name='\u91cd\u542f\u65f6\u95f4')),
                ('sjdinterface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.OpenInterface', verbose_name='\u9152\u5e97\u63a5\u53e3')),
            ],
            options={
                'verbose_name': '\u63a5\u53e3\u8fd0\u884c\u72b6\u6001',
                'verbose_name_plural': '\u63a5\u53e3\u8fd0\u884c\u72b6\u6001',
            },
        ),
        migrations.CreateModel(
            name='StatuTCPserver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20, verbose_name='IP')),
                ('port', models.IntegerField(verbose_name='\u7aef\u53e3')),
                ('nummax', models.IntegerField(verbose_name='\u6700\u5927\u8fde\u63a5\u6570')),
                ('booleanTCP', models.CharField(choices=[('on', '\u5f00'), ('off', '\u5173')], default='off', max_length=6)),
            ],
            options={
                'verbose_name': '\u670d\u52a1\u7aef',
                'verbose_name_plural': '\u670d\u52a1\u7aef',
            },
        ),
    ]
