# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-04 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusinterface',
            old_name='sjdinterface',
            new_name='hootelname',
        ),
        migrations.AlterField(
            model_name='statusinterface',
            name='portvercode',
            field=models.CharField(default='0c33fe70-f0f4-11e7-9162-201a0621d396', max_length=150, verbose_name='\u63a5\u53e3\u9a8c\u8bc1\u7801'),
        ),
        migrations.AlterField(
            model_name='statutcpserver',
            name='booleanTCP',
            field=models.CharField(choices=[('on', '\u5f00'), ('off', '\u5173')], default='off', max_length=6, verbose_name='\u5f00/\u5173'),
        ),
    ]
