# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-04 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20180104_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusinterface',
            name='hootelname',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='status.OpenInterface', verbose_name='\u9152\u5e97\u63a5\u53e3'),
        ),
        migrations.AlterField(
            model_name='statusinterface',
            name='portvercode',
            field=models.CharField(default='3d13a1c0-f0f5-11e7-9786-201a0621d396', max_length=150, verbose_name='\u63a5\u53e3\u9a8c\u8bc1\u7801'),
        ),
    ]
