# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-04 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0007_auto_20180104_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusinterface',
            name='portvercode',
            field=models.CharField(default='e4b78000-f0fe-11e7-8f27-201a0621d396', max_length=150, verbose_name='\u63a5\u53e3\u9a8c\u8bc1\u7801'),
        ),
    ]
