# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-16 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0008_auto_20180104_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='statutcpserver',
            name='beforenummax',
            field=models.IntegerField(default=0, verbose_name='\u5f53\u524d\u8fde\u63a5\u6570'),
        ),
        migrations.AlterField(
            model_name='statusinterface',
            name='portvercode',
            field=models.CharField(default='c1cdb211-fa6a-11e7-ad97-201a0621d396', max_length=150, verbose_name='\u63a5\u53e3\u9a8c\u8bc1\u7801'),
        ),
    ]
