# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-21 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0009_auto_20180116_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='statutcpserver',
            name='booleanTemplate',
            field=models.BooleanField(default=False, verbose_name='\u662f/\u5426'),
        ),
        migrations.AlterField(
            model_name='statusinterface',
            name='portvercode',
            field=models.CharField(default='d634a6d1-fe90-11e7-a232-201a0621d396', max_length=150, verbose_name='\u63a5\u53e3\u9a8c\u8bc1\u7801'),
        ),
    ]
